# Generated by Django 4.2.11 on 2024-05-03 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_mob_num_alter_user_pan_num_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mob_num",
            field=models.CharField(
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="pan_num",
            field=models.CharField(max_length=10),
        ),
    ]
