# Generated by Django 4.2.11 on 2024-05-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_mob_num_alter_user_pan_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="mob_num",
            field=models.CharField(max_length=17),
        ),
    ]
