# Generated by Django 4.2.11 on 2024-05-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_manager_active_alter_user_mob_num"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manager",
            name="active",
        ),
        migrations.AddField(
            model_name="manager",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
